apiVersion: v1
kind: Service
metadata:
  name: devops-application-service
spec:
  selector:
    app: devops-application
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
