# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: autopilot-cluster-1    # TODO: update to cluster name
  GKE_ZONE: us-central1-b #us-central1-c us-central1-f us-central1-a us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: devops-application-deployment # TODO: update to deployment name
  REPOSITORY: github-actions # TODO: update to Artifact Registry docker repository
  IMAGE: static-site
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Run Automation Tests
        run: mvn test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Dockerfile Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerfile Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Docker/Dockerfile
          push: true
          tags: javajvm007/devops-github-actions:latest

      # Alternative option - authentication via credentials json
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#      - name: Push Docker Image to Google Artifactory Registry ( GAR )
#        uses: par-tec/docker-push-gar-image@latest
#        with:
#          image_name: myimage
#          image_tag: latest
#          gar_hostname: us-central1-docker.pkg.dev
#          gar_project: $PROJECT_ID
#          gar_service_account: ${{ secrets.GCLOUD_SERVICE_KEY }}

# Deploying to GAR
#      - uses: actions/checkout@v3
#      - name: Authenticate to Google Cloud
#        id: auth
#        uses: google-github-actions/auth@v0
#        with:
#          workload_identity_provider: projects/123123123/locations/global/workloadIdentityPools/the-workload-pool/providers/the-provider
#          service_account: only-storage-object-adm@<PROJECT_ID>.iam.gserviceaccount.com

      - name: Push Docker Image to Google Artifactory Registry ( GAR )
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
          registry: gcr.io
          project_id: calm-depot-383818  # read from secrets
          image_name:  github-actions
          image_tag: latest,v1
          dockerfile: ./Docker/Dockerfile
          context: .

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: autopilot-cluster-1
          location: us-central1-a
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image gcr.io/calm-depot-383818/IMAGE:TAG=gcr.io/calm-depot-383818/github-actions:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide

# Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
